<a href="https://colab.research.google.com/github/D4rsh11/PyTorch/blob/main/Chapter_0_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Chapter 0: PyTorch Fundamentals

In [40]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors

### Creating tensors

In [41]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [42]:
scalar.ndim

0

In [43]:
# Get tensor back as Python int
scalar.item()

7

In [44]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [45]:
vector.ndim

1

In [46]:
vector.shape

torch.Size([2])

In [47]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [48]:
MATRIX.ndim

2

In [49]:
MATRIX[0]

tensor([7, 8])

In [50]:
MATRIX[1]

tensor([ 9, 10])

In [51]:
MATRIX.shape

torch.Size([2, 2])

In [52]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [53]:
TENSOR.ndim

3

In [54]:
TENSOR.shape

torch.Size([1, 3, 3])

In [55]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data  -> update random numbers -> look at data -> update random numbers`

Torch random tensors- https://docs.pytorch.org/docs/2.13/generated/torch.rand.html




In [56]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9802, 0.4017, 0.5931, 0.1730],
        [0.3127, 0.8837, 0.9647, 0.2748],
        [0.0579, 0.1900, 0.6793, 0.4543]])

In [57]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [58]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [61]:
ones.dtype

torch.float32

In [62]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [63]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [65]:
#Flot 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor(e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False)# whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [66]:
float_32_tensor.dtype

torch.float32

In [67]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [68]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [69]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [70]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [71]:
# Create a tenosr
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1533, 0.2416, 0.9711, 0.1459],
        [0.6856, 0.3819, 0.4894, 0.3226],
        [0.2662, 0.7719, 0.6779, 0.2175]])

In [72]:
# Find out detail about somw tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1533, 0.2416, 0.9711, 0.1459],
        [0.6856, 0.3819, 0.4894, 0.3226],
        [0.2662, 0.7719, 0.6779, 0.2175]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [73]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [74]:
# Multipy tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
tensor

tensor([1, 2, 3])

In [76]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [79]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)


tensor([10, 20, 30])

In [80]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in nerual networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (Dot product)

More information on multiplying matrices- https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [93]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6555, 0.6112, 0.6968],
        [0.8140, 0.4536, 0.6139],
        [0.9458, 0.3821, 0.5940]])

In [83]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [84]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [85]:
tensor

tensor([1, 2, 3])

In [86]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [88]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.64 ms, sys: 0 ns, total: 1.64 ms
Wall time: 1.41 ms


In [89]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 415 µs, sys: 0 ns, total: 415 µs
Wall time: 349 µs


tensor(14)

Matrix multiplication site: http://matrixmultiplication.xyz/

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shape for matrix mulitplication
tensor_A =