<a href="https://colab.research.google.com/github/D4rsh11/PyTorch/blob/main/Chapter_0_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Chapter 0: PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors

### Creating tensors

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data  -> update random numbers -> look at data -> update random numbers`

Torch random tensors- https://docs.pytorch.org/docs/2.13/generated/torch.rand.html




In [17]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2330, 0.2492, 0.9367, 0.5786],
        [0.7726, 0.6440, 0.9762, 0.6769],
        [0.3479, 0.7750, 0.5758, 0.5663]])

In [18]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [26]:
#Flot 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor(e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False)# whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [32]:
# Create a tenosr
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1055, 0.5679, 0.8015, 0.3544],
        [0.7091, 0.2406, 0.2335, 0.2691],
        [0.6065, 0.8885, 0.5763, 0.9864]])

In [33]:
# Find out detail about somw tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1055, 0.5679, 0.8015, 0.3544],
        [0.7091, 0.2406, 0.2335, 0.2691],
        [0.6065, 0.8885, 0.5763, 0.9864]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [35]:
# Multipy tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [38]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)


tensor([10, 20, 30])

In [39]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in nerual networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (Dot product)

More information on multiplying matrices- https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [40]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2890, 0.6432, 0.1421],
        [0.8663, 0.7709, 0.7446],
        [1.0396, 0.8162, 0.9235]])

In [41]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.55 ms, sys: 118 µs, total: 1.67 ms
Wall time: 5.31 ms


In [46]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 309 µs, sys: 43 µs, total: 352 µs
Wall time: 394 µs


tensor(14)

Matrix multiplication site: http://matrixmultiplication.xyz/

### One of the most common errors in deep learning: shape errors

In [47]:
# Shape for matrix mulitplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(It's an alias for writing less code)
#torch.matmul(tensor_A, tensor_B)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}(same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output=torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])(same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc(Tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [53]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [54]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [55]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [57]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(1)

In [60]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [61]:
x[9]

tensor(91)

## Reshaping, stackining, sequeezing and  unsqueesing tensor

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the smae memeory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimension to a target tensor
* Permute - Return a view of the input with dimentions permuted ( swapped) in a certain way


In [85]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [86]:
# Add an extra dimention
x_reshaped = x.reshape((1, 9))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [89]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [97]:
# torch.squeeze() - removes all single dimentions from a traget tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [98]:
# torch.unsqueeze() -  adds a single dimention to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [99]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [hight, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"Previous shape: {x_permuted.shape}")  # [colour_channels, hight, width]

Previous shape: torch.Size([224, 224, 3])
Previous shape: torch.Size([3, 224, 224])


In [106]:
# Something to play around
x_original[0, 0, 0]
x_original[0, 0, 0] = 74258

x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(74258.), tensor(74258.))

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [109]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [110]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [112]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [116]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [117]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [118]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:, 1]

tensor([[2, 5, 8]])

In [119]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [120]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [124]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3,6,9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And becuase of this, PyTorch has functionality to interact with it.  

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor


In [ ]:
arra.dtype